
fun problemFunction() {

}

fun main() {
    try {
        problemFunction()
    } catch (e: Exception) {
        println(e.message)
    }
}

